version: '3'
services:
    db:
        image: mysql:latest
        container_name: dbserver
        restart: always
        volumes:
            - './storage/mysql:/var/lib/mysql'
        environment:
            - MYSQL_ROOT_PASSWORD=rkskekfk1234!@#$
            - MYSQL_DATABASE=ennaru
            - TZ=Asia/Seoul
        ports:
            - "3306:3306"
volumes:
    server_volume:
        external: true