version: '3'
services:
    db:
        image: mysql:latest
        container_name: dbserver
        restart: always
        volumes:
            - './storage/mysql:/var/lib/mysql'
        environment:
            - MYSQL_ROOT_PASSWORD=rkskekfk1234!@#$
            - MYSQL_DATABASE=ennaru
            - TZ=Asia/Seoul
        ports:
            - "3306:3306"

    nginx:
        image: nginx:latest
        container_name: docker-web-nginx-1
        volumes:
            - './config/nginx/nginx.conf:/etc/nginx/nginx.conf'
            - './storage/nginx_log:/var/log/nginx'
        ports:
            - "8080:80"
    redis:
        image: redis:latest
        container_name: docker-redis
        command: redis-server /usr/local/etc/redis/redis.conf
        volumes:
            - './config/redis/redis.conf:/usr/local/etc/redis/redis.conf'
        ports:
            - "6379:6379"
        restart: always
volumes:
    server_volume:
        external: true