version: '3.6'
services:
    db:
        image: mysql:latest
        container_name: dbserver
        restart: always
        volumes:
            - './storage/mysql:/var/lib/mysql'
        environment:
            - MYSQL_ROOT_PASSWORD=rkskekfk1234!@#$
            - MYSQL_DATABASE=ennaru
            - TZ=Asia/Seoul
        ports:
            - "3306:3306"

    nginx:
        image: nginx:latest
        container_name: docker-web-nginx-1
        volumes:
            - './config/nginx/nginx.conf:/etc/nginx/nginx.conf'
            - './storage/nginx_log:/var/log/nginx'
        ports:
            - "8080:80"
    redis:
        image: redis:latest
        container_name: docker-redis
        #command: redis-server /usr/local/etc/redis/redis.conf
        volumes:
            - './config/redis/redis.conf:/usr/local/etc/redis/redis.conf'
        ports:
            - "6379:6379"
    gitlab:
        image: gitlab/gitlab-ce:latest
        container_name: docker-gitlab
        hostname: localhost
        environment:
            TZ: 'Asia/Seoul'
            GITLAB_OMNIBUS_CONFIG: |
                external_url 'http://localhost:7000'
                gitlab_rails['gitlab_shell_ssh_port'] = 7001
        ports:
            - "7000:80"
            - "7001:22"
            - '443:443'
        volumes:
            - './gitlab/config:/etc/gitlab'
            - './gitlab/logs:/var/log/gitlab'
            - './gitlab/data:/var/opt/gitlab'
        restart: always
        shm_size: '256m'
volumes:
    server_volume:
        external: true