version: '3'
services:
    db:
        image: mysql:latest
        container_name: dbserver
        restart: always
        volumes:
            - './storage/mysql:/var/lib/mysql'
        environment:
            - MYSQL_ROOT_PASSWORD=rkskekfk1234!@#$
            - MYSQL_DATABASE=sa
            - TZ=Asia/Seoul
        ports:
            - "3306:3306"
    nginx:
        image: nginx:latest
        #build: 
            #context: /web        
        container_name: nginx
        restart: always
        ports:
            - "80:80"
    nexus:
        platform: linux/amd64/v8
        image: sonatype/nexus3:latest
        container_name: nexus3
        restart: always
        volumes:
            - "./storage:/nexus-data"
        ports: 
            - "8081:8081"
    # jenkins:
    #     image: jenkins/jenkins:jdk17
    #     container_name: jenkins
    #     restart: always
    #     environment:
    #         - TZ=Asia/Seoul
    #     volumes:
    #        - ./server_volume/jenkins_storage2:/var/jenkins_home
    #     ports: 
    #     - '4000:8080'
    # gitbucket:
    #     image: gitbucket/gitbucket:latest
    #     container_name: gitbucket
    #     restart: always
    #     environment:
    #         - TZ=Asia/Seoul
    #     #/root/.gitbucket
    #     ports: 
    #     - '3000:8080'
    #     - '29418:29418'
#     gitlab:
#         platform: linux/amd64
#         container_name: gitlab
#         image: 'gitlab/gitlab-ce'
#         restart: always
#         hostname: '127.0.0.1'
#         environment:
#             GITLAB_OMNIBUS_CONFIG: |
#                 external_url 'http://127.0.0.1'
#             TZ: 'Asia/Seoul'
#         ports:
#         - '8080:80'
#         - '8443:443'
#         volumes:
#         - './server_volume/config:/etc/gitlab'
#         - './server_volume/logs:/var/log/gitlab'
#         - './server_volume/data:/var/opt/gitlab'
#         shm_size: '256m'
#         networks:
#             - gitlab
# networks:
#   gitlab:
#     name: gitlab-network
volumes:
    server_volume:
        external: true

#    dbserver exited with code 1
#gitlab    | 2023-10-05T11:14:16.110100009Z <jemalloc>: MADV_DONTNEED does not work (memset will be used instead)
#2023-10-05 20:14:16 gitlab    | <jemalloc>: (This is the expected behaviour if you are running under QEMU)